### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by AllinProgram** [ReyKoxha/nodebb-webview#10]
When the user edits and uploads the avatar in the app，app will force close， on most of Huawei and Xiaomi ，I guess this is because the Android version of phone is higher than 8.1，I am sorry that I can't solve this problem，it has been bothering me for a long time，I hope to get your help .

**Comment by ReyKoxha** [comment]
Hello ufan0.
I am really sorry that I did not see this issue before.
The code most likely needs to be updated to work with Android 8 or newer.
Especially now since we have AndroidX.

Since, I do not use NodeBB anymore, I didn't update this code since a long time and actually do not want to bother with it as well, since my time became rare.

Therefore, I will see if I can fix this some day - or someone is faster and opens a PR to fix your issue.
